version: '3'
services:
    api:
      build: .
      depends_on:
          - postgres
      ports:
          - 8000:8000
      environment:
          - DATABASE_HOSTNAME=postgres
          - DATABASE_PORT=5432
          - DATABASE_PASSWORD=MMartx$$5pst
          - DATABASE_NAME=fastapi
          - DATABASE_USERNAME=postgres
          - SECRET_KEY=2039584857203874019jdsdkfj283rh0jnaoug497302h3rfkjfh92310h
          - ALGORITHM=HS256
          - ACCESS_TOKEN_EXPIRE_MINUTES=30

    postgres:
      image: postgres
      environment:
          - POSTGRES_PASSWORD=password123
          - POSTGRES_DB=fastapi

      volumes:
          - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db: